### ISSUE TITLE
[PE-D][Tester B] Add command still creates openings with existing company and position

### ISSUE THREAD

**Issue by nus-se-script** [AY2223S2-CS2103T-F12-4/tp#163]
In the UG, it is stated that "If both COMPANY and POSITION of a new opening matches a current opening, the new opening will not be added."

This does work as stated in the UG, however a COMPANY and POSITION matching is not case insensitive. Consider making the matching case insensitive so that repeated openings cannot be added just by changing their casing.

To recreate this bug, i followed these steps

1. add p/Data Analyst c/Apple e/apple@gmail.com s/offered [Added successfully]
2. add p/data analyst c/Apple e/peach@gmail.com s/rejected [Added successfully]
3. add p/Data Analyst c/Apple e/apple@gmail.com s/offered [Opening already exists error]

![image.png](https://raw.githubusercontent.com/TabrizPlv/ped/main/files/2d767957-b928-4147-b869-928d1c63352e.png)

-------------
Labels: `severity.Medium` `type.FunctionalityBug`
original: TabrizPlv/ped#3

**Comment by Lanreath** [comment]
Duplicate issue
